#pragma once

// Single-file web UI served from flash -- no external assets, no internet
// needed (the whole point of the SoftAP setup). Talks to the board over
// three tiny JSON endpoints: GET /state, POST /move, POST /reset.
static const char INDEX_HTML[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<title>Ultimate Tic-Tac-Toe AI</title>"
"<style>"
"body{font-family:sans-serif;background:#111;color:#eee;display:flex;"
"flex-direction:column;align-items:center;padding:16px;margin:0}"
"h1{font-size:18px;margin:8px 0}"
"#status{margin:8px 0;min-height:20px;font-size:14px;text-align:center}"
"#board{display:grid;grid-template-columns:repeat(9,1fr);gap:2px;"
"width:min(92vw,420px);aspect-ratio:1;background:#444}"
".cell{display:flex;align-items:center;justify-content:center;"
"background:#222;font-size:4vw;max-font-size:20px;cursor:pointer;"
"user-select:none}"
".cell.legal{background:#1c3a1c}"
".cell.x{color:#4da6ff}"
".cell.o{color:#ff6b6b}"
".sub-won-1{background:rgba(77,166,255,0.15)}"
".sub-won--1{background:rgba(255,107,107,0.15)}"
".b-right{border-right:2px solid #999}"
".b-bottom{border-bottom:2px solid #999}"
"button{margin-top:14px;padding:8px 18px;font-size:14px;border:0;"
"border-radius:6px;background:#2a5;color:#fff;cursor:pointer}"
"</style></head><body>"
"<h1>Ultimate Tic-Tac-Toe -- you are O, board plays X</h1>"
"<div id='status'>loading...</div>"
"<div id='board'></div>"
"<button onclick='doReset()'>New game</button>"
"<script>"
"const boardEl=document.getElementById('board');"
"const statusEl=document.getElementById('status');"
"let state=null;"
"function cellIndex(sub,cell){"
"const br=Math.floor(sub/3),bc=sub%3,cr=Math.floor(cell/3),cc=cell%3;"
"const row=br*3+cr,col=bc*3+cc;return row*9+col;}"
"function render(){"
"boardEl.innerHTML='';"
"const grid=new Array(81).fill(null);"
"for(let s=0;s<9;s++)for(let c=0;c<9;c++){"
"grid[cellIndex(s,c)]={sub:s,cell:c,v:state.board[s*9+c]};}"
"const legalSubs=new Set();"
"for(let s=0;s<9;s++){"
"if(state.subResult[s]!==0)continue;"
"if(state.activeSub===-1||state.activeSub===s)legalSubs.add(s);}"
"for(let row=0;row<9;row++){"
"for(let col=0;col<9;col++){"
"const idx=row*9+col;const info=grid[idx];"
"const div=document.createElement('div');"
"div.className='cell';"
"if((col+1)%3===0&&col!==8)div.className+=' b-right';"
"if((row+1)%3===0&&row!==8)div.className+=' b-bottom';"
"if(state.subResult[info.sub]===1)div.className+=' sub-won-1';"
"if(state.subResult[info.sub]===-1)div.className+=' sub-won--1';"
"if(info.v===1){div.textContent='X';div.className+=' x';}"
"else if(info.v===-1){div.textContent='O';div.className+=' o';}"
"else{"
"const canPlay=!state.done&&state.player===-1&&"
"legalSubs.has(info.sub)&&info.v===0;"
"if(canPlay){"
"div.className+=' legal';"
"div.onclick=()=>doMove(info.sub,info.cell);"
"}}"
"boardEl.appendChild(div);"
"}}"
"let msg='';"
"if(state.done){"
"if(state.winner===1)msg='Board (X) wins!';"
"else if(state.winner===-1)msg='You (O) win!';"
"else msg='Draw.';"
"}else if(state.error){"
"msg='Illegal move, try another cell.';"
"}else{"
"msg=state.player===-1?'Your turn (O)':'Board is thinking...';"
"}"
"statusEl.textContent=msg;"
"}"
"async function fetchState(){"
"const r=await fetch('/state');state=await r.json();render();}"
"async function doMove(sub,cell){"
"const r=await fetch('/move',{method:'POST',"
"body:JSON.stringify({sub:sub,cell:cell})});"
"state=await r.json();render();}"
"async function doReset(){"
"const r=await fetch('/reset',{method:'POST'});"
"state=await r.json();render();}"
"fetchState();"
"</script></body></html>";
