"""Export trained NumPy params (.npz) to a C header with float32 arrays.

Model is tiny (~93KB as float32), so we skip INT8 quantization entirely --
flash on the ESP32-S3 (8MB) has plenty of room, and it keeps the C inference
code (and this export script) dead simple.
"""
import argparse
import numpy as np


def c_array(name, arr):
    flat = arr.flatten().astype(np.float32)
    vals = ", ".join(f"{v:.8f}f" for v in flat)
    shape_comment = "x".join(str(d) for d in arr.shape)
    return (f"// shape: {shape_comment}\n"
            f"static const float {name}[{flat.size}] = {{{vals}}};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("npz_path")
    ap.add_argument("--out", default="../main/model_weights.h")
    args = ap.parse_args()

    data = np.load(args.npz_path)
    params = {k: data[k] for k in data.files}

    lines = [
        "// Auto-generated by export_weights.py -- do not edit by hand.",
        "#pragma once",
        "",
    ]
    name_map = {
        "W1": "g_W1", "b1": "g_b1",
        "W2": "g_W2", "b2": "g_b2",
        "Wp": "g_Wp", "bp": "g_bp",
        "Wv": "g_Wv", "bv": "g_bv",
    }
    for key, cname in name_map.items():
        lines.append(c_array(cname, params[key]))

    lines.append(f"#define INPUT_DIM {params['W1'].shape[0]}")
    lines.append(f"#define H1_DIM {params['W1'].shape[1]}")
    lines.append(f"#define H2_DIM {params['W2'].shape[1]}")
    lines.append(f"#define POLICY_DIM {params['Wp'].shape[1]}")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    total_bytes = sum(params[k].size for k in name_map) * 4
    print(f"wrote {args.out}  ({total_bytes/1024:.1f} KB as float32)")


if __name__ == "__main__":
    main()
